name: Deploy dynamodb reources in all environment
on:
  push:
    paths:
      - 'Dev/Dynamodb/**'
      - 'Stage/Dynamodb/**'
      - 'Perf/Dynamodb/**'
      - 'Uat/Dynamodb/**'
      - 'Main/Dynamodb/**'

jobs:
  Development:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  Stage:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  UAT:
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  Perf:
    if: github.ref == 'refs/heads/perf'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  Main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4