name: Deploy s3 reources in all environment
on:
  push:
    branches:
      - dev
      - stage
      - uat
      - perf
jobs:
  Development:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  Stage:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  UAT:
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  Perf:
    if: github.ref == 'refs/heads/perf'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4

  Main:
    if: github.ref == 'refs/heads/main11'
    runs-on: ubuntu-latest
    steps:
      - id: CheckOut
        name: Checkout Repository
        uses: actions/checkout@v4